name: 'Setup Laravel'
description: 'Custom setup action for Laravel applications'
inputs:
  php-version:
    required: false
    default: 8.0
  cache-composer:
    required: false
    default: true
  env:
    required: false
    default: testing
  mysql-database:
    required: false
  node-version:
    required: true
  node-package-manager:
    required: true

runs:
  using: composite
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}

    - name: Get composer cache directory
      id: composer-cache
      shell: bash
      if: ${{ inputs.cache-composer }}
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      if: ${{ inputs.cache-composer }}
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install composer dependencies
      shell: bash
      run: composer install --prefer-dist

    - uses: actions/setup-node@v2
      if: inputs.node-package-manager
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-package-manager }}

    - name: Install node dependencies
      shell: bash
      if: inputs.node-package-manager
      run: ${{ inputs.node-package-manager }} install

    - name: Start MySQL database
      shell: bash
      env:
        CREATE_DATABASE_COMMAND: "CREATE DATABASE ${{ inputs.mysql-database }};"
      if: inputs.mysql-database
      run: |
        sudo systemctl start mysql
        mysql -uroot -proot --execute="${{ env.CREATE_DATABASE_COMMAND }}"
