name: test composite action

on:
  push:
    branches: main
    tags: v1

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: composer init -n --name "melhorenvio/setup-php"

      - uses: melhor-envio/setup-php@v1
        with:
          php-version: '8.0'
          cache-composer: true
          env: 'testing'
